// TO VAN HUONG - PAUL TO - VIET NAM
import ALogin from './pages/admin/ALogin';
import Introduction from './pages/Introduction';
import Home from './pages/Home'
import EmployeeDashboard from './pages/EmployeeDashboard';
import AdminDashboard from './pages/AdminDashboard';
import NLogin from './pages/client/NLogin';
import CatIcon from './assets/cat+icon.png';
import CatDrinksMilkTeaGif from './assets/cat+drink+milk+tea.gif';
import NavigationBar from './components/NavigationBar';
import StockDetails from './pages/StockDetails';
import AddStockInfo from './pages/client/AddStockInfo';
import AddStaff from './pages/admin/AddStaff';
import Notification from './components/Notification';
import UpdateBranch from './pages/admin/UpdateBranch';
import StaffDashboard from './pages/client/StaffDashboard';
import SideBar from './components/SideBar';
import Loading from './components/Loading';
import ConfirmDialog from './components/ConfirmDialog';
import ErrorPage from './components/ErrorPage';
import SideBarOfAdmin from './components/SideBarOfAdmin';
import UpdateRemainStock from './components/UpdateRemainStock';
import ReportModal from './components/ReportModal';
import UpdateReportModal from './components/UpdateReportModal';
import ModifyStockDataInADay from './components/ModifyStockDataInADay';
import ApprovePage from './pages/ApprovePage';
import Container from './components/Container';
import ApprovePageTab02 from './pages/ApprovePageTab02';
export { ApprovePageTab02, Container, CatDrinksMilkTeaGif, ApprovePage, ModifyStockDataInADay, UpdateReportModal, ReportModal, UpdateRemainStock, SideBarOfAdmin, ErrorPage, ConfirmDialog, Loading, SideBar, StaffDashboard, UpdateBranch, Notification, NLogin, ALogin, Introduction, Home, EmployeeDashboard, AdminDashboard, CatIcon, NavigationBar, AddStaff, StockDetails, AddStockInfo };